server:
  port: 8088

spring:
  application:
    name: cloud-feign-customer
  cloud:
    nacos:
      discovery:
        namespace: 14198254-40cb-49f4-85b7-afad8042aede
        server-addr: 10.3.133.160:8848

# 负载均衡的配置
# 服务端不涉及远程可以不需要配置
feign:
  # 使用okhttp作为底层通信框架
  okhttp:
    enabled: true